
###################################################
# this(CMakeTestAutoGeneration.cmake) is automatically generated by 'auto_ctest_impl.py'. 
# The behavior of modifying this file is undefined.
###################################################
message(STATUS "load ctests automatic generated success")

add_test(NAME "${CMAKE_BINARY_DIR}/spectrum" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/spectrum")
set_tests_properties("${CMAKE_BINARY_DIR}/spectrum" PROPERTIES LABELS "golden;")
    
add_test(NAME "${CMAKE_BINARY_DIR}/fft_test" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src ${CMAKE_BINARY_DIR}/fft_test")
set_tests_properties("${CMAKE_BINARY_DIR}/fft_test" PROPERTIES LABELS "golden;")
    